var TI;"undefined"!=typeof Titanium?TI=Titanium:"undefined"!=typeof Ti&&(TI=Ti);Object.size=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};function os(){return TI.App.getHome().match(/Contents/)?"osx":TI.App.getHome().match(/\.pia_manager/)?"linux":"win"}TI.API.setLogLevel(TI.API.TRACE);for(var env=TI.API.getEnvironment(),pia_manager_dir,nolog,bs="",i=0;8192>i;i++)bs+=" ";bs+="\n";
function log(a){if(!nolog&&(TI.API.info(a),main_window().log_file)){var b=new Date,b="["+b.getMonth()+"/"+b.getDate()+"/"+b.getYear()+" "+b.getHours()+":"+b.getMinutes()+":"+b.getSeconds()+"] ";main_window().log_file.write(b+a+"\n");main_window().log_file.seek(8192,TI.Filesystem.SEEK_CURRENT);main_window().log_file.write(" ");main_window().log_file.seek(-8193,TI.Filesystem.SEEK_CURRENT)}}
try{pia_manager_dir=env.PIA_MANAGER_DIR;var settings_file=TI.Filesystem.getFile(pia_manager_dir,"data","settings.json")}catch(e$$8){log("pia_manager_dir error: "+e$$8)}nolog=TI.Filesystem.getFile(pia_manager_dir,"nolog").exists();try{!nolog&&!main_window().log_file&&(main_window().log_file=TI.Filesystem.getFile(pia_manager_dir,"log","pia_tray."+parseInt((new Date).getTime()/1E3)+".log").open(TI.Filesystem.MODE_WRITE,!0))}catch(e$$9){log("error setting up logfile: "+e$$9)}
main_window().canceled_timers||(main_window().canceled_timers={});function set_timeout(a,b){var c=Math.random().toString();main_window().canceled_timers[c]=false;setTimeout(function(){main_window().canceled_timers[c]||a();delete main_window().canceled_timers[c]},b);return c}function clear_timeout(a){main_window().canceled_timers[a]=true}function space_pad(a,b){for(var c=a,d=0;d<b-a.length;d++)c=c+" ";return c}
for(log("opening command file");!main_window().command_file;)try{main_window().command_file||(main_window().command_file=TI.Filesystem.getFile(pia_manager_dir,"data","command_file.txt").open(TI.Filesystem.MODE_WRITE,!0),main_window().command_file_cnt=0)}catch(e$$10){log("command_file: "+e$$10)}
function daemon_cmd(a,b,c){if(a=="connection_status"||a=="notifications"||a=="vpn_ports"||a=="regions"||a=="latency_status"||a=="openvpn_status"||a=="need_upgrade"||a=="forwarded_port"||a=="connect_ip"||a=="region_name")return status_from_file(a,c);b||(b={});delete b.sync;b.cmd=a;b.pass&&(b.pass=enc(b.pass));a=TI.JSON.stringify(b);b.pass&&(b.pass="");var b=TI.JSON.stringify(b),c=main_window().command_file_cnt,d=c%100*32768;main_window().command_file.seek(d,TI.Filesystem.SEEK_START);main_window().command_file.write(a+
"\u0001");main_window().command_file.seek(d+16384,TI.Filesystem.SEEK_START);main_window().command_file.write(c.toString()+"\u0001");main_window().command_file.seek(3276800,TI.Filesystem.SEEK_START);main_window().command_file.write(" ");main_window().command_file_cnt=c+1;log("sent cmd: "+c+": "+b)}
try{main_window().status_file||(main_window().status_file=TI.Filesystem.getFile(pia_manager_dir,"data","status_file.txt").open(TI.Filesystem.MODE_READ,!0),log("created status file: "+main_window().status_file))}catch(e$$11){log("status_file open: "+e$$11)}var status_locations={connection_status:0,vpn_ports:1,regions:2,latency_status:3,notifications:4,openvpn_status:5,need_upgrade:6,forwarded_port:7,connect_ip:8,region_name:9};
function status_from_file(a,b){try{main_window().status_file.seek(status_locations[a]*1E4,TI.Filesystem.SEEK_START);var c=main_window().status_file.read(1E4).substr(0),d=c.indexOf("\u0001");d==-1?log(""+a+": no zero byte found!"):c=c.substring(0,d);c=c.replace(/^\s*|\s*$/g,"");try{var e=TI.JSON.parse(c);b&&b(e)}catch(f){log("json: "+c+" -- "+f)}}catch(g){log("status_from_file: "+a+": "+g)}}function settingsq(a){return settings_window().settingsq(a)}
function settings_window(){return TI.UI.getWindows()[1]}function main_window(){return TI.UI.getWindows()[0]}function enc(a){return"\x00\x00\x00\x00"+o(a)}function dec(a){return a.substr(0,4)!="\x00\x00\x00\x00"?a:o(a.substr(4))}function o(a){for(var b="",c=0;c<a.length&&c<121;++c)b=b+String.fromCharCode(a.charCodeAt(c)^"GN\\\\Lqnw-xc]=jQ}fTyN[Y|x5Db-FET?&)T#{f@6qK3q>C?[9z.1u.o0;+-Hf^7^MfRBmvAJ@zZu:-aQeAr.$h0u2y{iy/5<0A`)KZQ8vcP'vVm3DS@{_{y.i".charCodeAt(c));return b}
function setting(a,b){var c=read_settings();if(typeof b=="undefined")return c[a];c[a]=b;write_settings(c)}function read_settings(){if(!settings_file.exists())return{};var a=settings_file.open(TI.Filesystem.MODE_READ,true),b=a.read(16384);a.close();try{var c=TI.JSON.parse(b);c.pass&&(c.pass=dec(c.pass));return c}catch(d){log("read settings: "+d);return{}}}
function write_settings(a){a.pass&&(a.pass=enc(a.pass));var b=settings_file.open(TI.Filesystem.MODE_WRITE,true);b.write(TI.JSON.stringify(a));b.close()}
function settings_window_show(){settingsq("#proto").val(setting("proto"));settings_window_update();settingsq("#username").val(setting("user"));settingsq("#password").val(setting("pass"));settingsq("#region").val(setting("region"));settingsq("#rport").val(setting("rport"));settingsq("#lport").val(setting("lport"));settingsq("#symmetric_cipher").val(setting("symmetric_cipher"));settingsq("#symmetric_auth").val(setting("symmetric_auth"));settingsq("#handshake_enc").val(setting("handshake_enc"));settingsq("#portforward").prop("checked",
setting("portforward"));settingsq("#killswitch").prop("checked",setting("killswitch"));settingsq("#dnsleak").prop("checked",setting("dnsleak"));settingsq("#ipv6leak").prop("checked",setting("ipv6leak"));settingsq("#connect_on_startup").prop("checked",setting("connect_on_startup"));settingsq("#run_on_startup").prop("checked",setting("run_on_startup"));settings_window().show();settings_window().check_enc()}
function settings_window_save(){setting("user",settingsq("#username").val().replace(/^\s*|\s*$/g,""));setting("pass",settingsq("#password").val().replace(/^\s*|\s*$/g,""));setting("region",settingsq("#region").val());setting("proto",settingsq("#proto").val());setting("rport",settingsq("#rport").val());setting("lport",settingsq("#lport").val());setting("symmetric_cipher",settingsq("#symmetric_cipher").val());setting("symmetric_auth",settingsq("#symmetric_auth").val());setting("handshake_enc",settingsq("#handshake_enc").val());
setting("portforward",settingsq("#portforward").prop("checked"));setting("killswitch",settingsq("#killswitch").prop("checked"));setting("dnsleak",settingsq("#dnsleak").prop("checked"));setting("ipv6leak",settingsq("#ipv6leak").prop("checked"));setting("connect_on_startup",settingsq("#connect_on_startup").prop("checked"));setting("run_on_startup",settingsq("#run_on_startup").prop("checked"));daemon_cmd("portforward",{value:setting("portforward")});daemon_cmd("killswitch",{value:setting("killswitch")});
daemon_cmd("dnsleak",{value:setting("dnsleak")});daemon_cmd("ipv6leak",{value:setting("ipv6leak")});main_window().set_daemon_user()}
function setup_default_settings(){setting("region")||setting("region","auto");setting("proto")||setting("proto","udp");setting("rport")||setting("rport","auto");setting("lport")||setting("lport","");setting("symmetric_cipher")||setting("symmetric_cipher","aes-128-cbc");setting("symmetric_auth")||setting("symmetric_auth","sha1");setting("handshake_enc")||setting("handshake_enc","rsa2048");setting("portforward")||setting("portforward",false);setting("killswitch")||setting("killswitch",false);setting("dnsleak")||
setting("dnsleak",false);setting("ipv6leak")==null&&setting("ipv6leak",true);setting("run_on_startup")||setting("run_on_startup",false);setting("connect_on_startup")||setting("connect_on_startup",false)}var html_cache={};function jq_obj(a){html_cache[a]||(html_cache[a]=$(a));return html_cache[a]}
function settings_window_update(){var a=settingsq("#region"),b=settingsq("#rport"),c=settingsq("#proto").val(),d=a.val(),e=b.val();a.find("option").remove();a.append(jq_obj('<option value="auto">auto</option>'));$.each(main_window().regions,function(b,c){a.append(jq_obj('<option value="'+c[0]+'">'+c[1]+"&nbsp;&nbsp;&nbsp;</option>"))});d&&a.val(d);b.find("option").remove();b.append(jq_obj("<option>auto</option>"));$.each(main_window().vpn_ports[c],function(a,c){b.append(jq_obj('<option value="'+c+
'">'+c+"&nbsp;&nbsp;&nbsp;</option>"))});e&&b.val(e)}function notification(){}
var CONTINENTS={AF:"Africa",AN:"Antarctica",AS:"Asia",EU:"Europe",NA:"North America",OC:"Oceania",SA:"South America"},COUNTRIES={AD:"EU",AE:"AS",AF:"AS",AG:"NA",AI:"NA",AL:"EU",AM:"AS",AO:"AF",AQ:"AN",AR:"SA",AS:"OC",AT:"EU",AU:"OC",AW:"NA",AX:"EU",AZ:"AS",BA:"EU",BB:"NA",BD:"AS",BE:"EU",BF:"AF",BG:"EU",BH:"AS",BI:"AF",BJ:"AF",BL:"NA",BM:"NA",BN:"AS",BO:"SA",BQ:"NA",BR:"SA",BS:"NA",BT:"AS",BV:"AN",BW:"AF",BY:"EU",BZ:"NA",CA:"NA",CC:"AS",CD:"AF",CF:"AF",CG:"AF",CH:"EU",CI:"AF",CK:"OC",CL:"SA",CM:"AF",
CN:"AS",CO:"SA",CR:"NA",CU:"NA",CV:"AF",CW:"NA",CX:"AS",CY:"EU",CZ:"EU",DE:"EU",DJ:"AF",DK:"EU",DM:"NA",DO:"NA",DZ:"AF",EC:"SA",EE:"EU",EG:"AF",EH:"AF",ER:"AF",ES:"EU",ET:"AF",FI:"EU",FJ:"OC",FK:"SA",FM:"OC",FO:"EU",FR:"EU",GA:"AF",GB:"EU",GD:"NA",GE:"AS",GF:"SA",GG:"EU",GH:"AF",GI:"EU",GL:"NA",GM:"AF",GN:"AF",GP:"NA",GQ:"AF",GR:"EU",GS:"AN",GT:"NA",GU:"OC",GW:"AF",GY:"SA",HK:"AS",HM:"AN",HN:"NA",HR:"EU",HT:"NA",HU:"EU",ID:"AS",IE:"EU",IL:"AS",IM:"EU",IN:"AS",IO:"AS",IQ:"AS",IR:"AS",IS:"EU",IT:"EU",
JE:"EU",JM:"NA",JO:"AS",JP:"AS",KE:"AF",KG:"AS",KH:"AS",KI:"OC",KM:"AF",KN:"NA",KP:"AS",KR:"AS",KW:"AS",KY:"NA",KZ:"AS",LA:"AS",LB:"AS",LC:"NA",LI:"EU",LK:"AS",LR:"AF",LS:"AF",LT:"EU",LU:"EU",LV:"EU",LY:"AF",MA:"AF",MC:"EU",MD:"EU",ME:"EU",MF:"NA",MG:"AF",MH:"OC",MK:"EU",ML:"AF",MM:"AS",MN:"AS",MO:"AS",MP:"OC",MQ:"NA",MR:"AF",MS:"NA",MT:"EU",MU:"AF",MV:"AS",MW:"AF",MX:"NA",MY:"AS",MZ:"AF",NA:"AF",NC:"OC",NE:"AF",NF:"OC",NG:"AF",NI:"NA",NL:"EU",NO:"EU",NP:"AS",NR:"OC",NU:"OC",NZ:"OC",OM:"AS",PA:"NA",
PE:"SA",PF:"OC",PG:"OC",PH:"AS",PK:"AS",PL:"EU",PM:"NA",PN:"OC",PR:"NA",PS:"AS",PT:"EU",PW:"OC",PY:"SA",QA:"AS",RE:"AF",RO:"EU",RS:"EU",RU:"EU",RW:"AF",SA:"AS",SB:"OC",SC:"AF",SD:"AF",SE:"EU",SG:"AS",SH:"AF",SI:"EU",SJ:"EU",SK:"EU",SL:"AF",SM:"EU",SN:"AF",SO:"AF",SR:"SA",SS:"AF",ST:"AF",SV:"NA",SX:"NA",SY:"AS",SZ:"AF",TC:"NA",TD:"AF",TF:"AN",TG:"AF",TH:"AS",TJ:"AS",TK:"OC",TL:"OC",TM:"AS",TN:"AF",TO:"OC",TR:"AS",TT:"NA",TV:"OC",TW:"AS",TZ:"AF",UA:"EU",UG:"AF",UM:"OC",US:"NA",UY:"SA",UZ:"AS",VA:"EU",
VC:"NA",VE:"SA",VG:"NA",VI:"NA",VN:"AS",VU:"OC",WF:"OC",WS:"OC",XK:"EU",YE:"AS",YT:"AF",ZA:"AF",ZM:"AF",ZW:"AF"};
