var TI;"undefined"!=typeof Titanium?TI=Titanium:"undefined"!=typeof Ti&&(TI=Ti);var sw=TI.UI.createWindow({id:"settings",url:"app://settings.html",title:"Settings",width:300,height:330,fullscreen:!1,resizable:!1,maximizable:!1,minimizable:!1,topMost:!0,visible:!0,closeable:!1});sw.hide();sw.open();main_window().vpn_ports={};main_window().latencies={};main_window().regions=[];function set_vpn_ports(a,b){main_window().vpn_ports=a;b||settings_window_update()}
function set_regions(a,b){main_window().regions=a;b||settings_window_update()}function set_latency_status(a){main_window().latencies=a;settings_window_update()}var connection_status=null,tray_connection_status,reconnect=!1,tray,trayMenu,tray_menu_status,tray_menu_connect,tray_menu_disconnect,tray_menu_connect_items=[],forwarded_port,connected_region;function check_notifications(a){a.bad_auth&&(reconnect=!1);a.no_tap_driver&&(reconnect=!1);a.cant_assign_requested_address&&(reconnect=!1)}
function set_connection_status(a){a!=connection_status&&("CONNECTED"==a?set_connected():"down"==a?set_disconnected():set_connecting());"CONNECTED"!=connection_status&&"CONNECTED"==a&&(setup_polling("connection_status",5E3,poll_connection_status),notification("VPN Connected"));"CONNECTED"==connection_status&&"CONNECTED"!=a&&(setup_polling("connection_status",5E3,poll_connection_status),notification("VPN Disconnected"));connection_status&&("down"!=connection_status&&"down"==a)&&daemon_cmd("notifications",
{},function(a){check_notifications(a)});if(connection_status&&"down"!=connection_status&&"down"==a&&reconnect)return log("connect() because set_connection_status: "+connection_status+" "+a),connect();connection_status=a}function set_openvpn_status(){}
function set_tray_hint(){var a=tray_connection_status;if("Connected"==tray_connection_status){var b,c;status_from_file("region_name",function(a){b=a.single});status_from_file("connect_ip",function(a){c=a.single});a=a+(" - "+b)+(" ("+c+")")}forwarded_port&&"Connected"==tray_connection_status&&(a+=" [ port: "+forwarded_port+" ]");tray.setHint(a);tray_menu_status.setLabel(a)}function set_forwarded_port(a){forwarded_port=a;set_tray_hint()}
function set_connected(){tray.setIcon("osx"==os()?"tray-mac-connected.png":"icon.png");tray_connection_status="Connected";set_tray_hint();$.each(tray_menu_connect_items,function(a,b){b.disable()});tray_menu_disconnect.enable()}function set_disconnected(){tray.setIcon("osx"==os()?"tray-mac-disconnected.png":"icon_d.png");tray_connection_status="Disconnected";set_tray_hint();$.each(tray_menu_connect_items,function(a,b){b.enable()});tray_menu_disconnect.disable()}
function set_connecting(){tray.setIcon("osx"==os()?"tray-mac-connecting.png":"icon_c.png");tray_connection_status="Connecting";set_tray_hint();$.each(tray_menu_connect_items,function(a,b){b.disable()});tray_menu_disconnect.enable()}var connect_times=[];
function connect(){forwarded_port=null;log("connect()");5<=connect_times.length&&18E4>new Date-connect_times[0]?(log("more than 5 connections in under 3 mins, wont reconnect"),reconnect=!1):reconnect=!0;connect_times.push(new Date);connect_times=connect_times.slice(-5);connection_status="down";notification("VPN Connecting");daemon_cmd("connect",{region:setting("region"),user:setting("user"),pass:setting("pass"),proto:"openvpn_"+setting("proto"),lport:setting("lport"),rport:setting("rport"),symmetric_cipher:setting("symmetric_cipher"),
symmetric_auth:setting("symmetric_auth"),handshake_enc:setting("handshake_enc")});connected_region=setting("region");setup_polling("connection_status",500,poll_connection_status)}function disconnect(a){a||(reconnect=!1);daemon_cmd("disconnect");setup_polling("connection_status",500,poll_connection_status)}main_window().polling_timers||(main_window().polling_timers={});
var setup_polling=function(a,b,c){log("setup polling: "+a+" "+b);stop_polling(a);var e=function(){main_window().polling_timers[a]=set_timeout(e,b);c()};main_window().polling_timers[a]=set_timeout(e,b)},stop_polling=function(a){if(main_window().polling_timers[a]){log("stop polling "+a);clear_timeout(main_window().polling_timers[a])}};function poll_connection_status(){daemon_cmd("connection_status",{},function(a){set_connection_status(a.single)})}
function connect_item_clicked(){setting("user")?connect():settings_window_show()}
main_window().setup=function(){function a(a){try{if(a&&!g){g=true;trayMenu.insertItemAt(TI.UI.createSeparatorMenuItem(),0);trayMenu.insertItemAt(TI.UI.createMenuItem("Upgrade Available",function(){os()=="osx"?TI.Process.createProcess(["open","https://www.privateinternetaccess.com/installer/download_installer_osx"]).launch():TI.Process.createProcess(["cmd","/C","start https://www.privateinternetaccess.com/installer/download_installer_win"]).launch()}),0)}}catch(b){log("upgrade: "+b)}}log("getting initial connection status");
var b=false;daemon_cmd("connection_status",{sync:true},function(a){b=a.single=="CONNECTED"});log("setting up tray");daemon_cmd("regions",{sync:true},function(a){set_regions(a,true)});tray=TI.UI.addTray(b?"icon.png":"icon_d.png");trayMenu=TI.UI.createMenu();tray.setHint("Private Internet Access");tray_menu_status=TI.UI.createMenuItem("");tray_menu_status.disable();if(os()=="linux"){trayMenu.appendItem(tray_menu_status);trayMenu.addSeparatorItem()}tray_menu_connect=TI.UI.createMenuItem("Connect",function(){connect_item_clicked()});
tray_menu_connect_items.push(tray_menu_connect);tray_menu_disconnect=TI.UI.createMenuItem("Disconnect",function(){disconnect()});var c=TI.UI.createMenuItem("Settings",function(){settings_window_show()}),e=TI.UI.createMenuItem("Exit",function(){TI.UI.clearTray();daemon_cmd("shutdown",{sync:true})}),m=TI.UI.createMenuItem("Send Slow Speed Complaint",function(){alert("Thank you! Your complaint will help us better identify and fix speed issues. Please feel free to submit a complaint anytime there are issues with your connection.");
daemon_cmd("complaint",{sync:true})});trayMenu.appendItem(tray_menu_connect);trayMenu.appendItem(tray_menu_disconnect);trayMenu.addSeparatorItem();var d=TI.UI.createMenuItem("Connect Auto",function(){setting("region","auto");connect_item_clicked()});trayMenu.appendItem(d);tray_menu_connect_items.push(d);var h=window.screen.height<=800,i=TI.UI.createMenu();$.each(main_window().regions,function(a,b){var c=TI.UI.createMenuItem("Connect "+b[1],function(){setting("region",b[0]);connect_item_clicked()});
h&&a>20?i.appendItem(c):trayMenu.appendItem(c);tray_menu_connect_items.push(c)});if(h){d=TI.UI.createMenuItem("More...");d.setSubmenu(i);trayMenu.appendItem(d)}trayMenu.addSeparatorItem();trayMenu.appendItem(c);trayMenu.appendItem(m);trayMenu.addSeparatorItem();trayMenu.appendItem(e);tray.setMenu(trayMenu);var g=false;try{TI.API.getEnvironment();var j=TI.Filesystem.getFile(pia_manager_dir,"tmp","pia_tray_shutdown.txt").open(TI.Filesystem.MODE_READ,true),k=function(){j.seek(0,TI.Filesystem.SEEK_START);
if(j.read(1)=="1"){log("pia_tray_shutdown.txt set, clearing tray");TI.UI.clearTray()}setTimeout(k,250)};k()}catch(n){}daemon_cmd("vpn_ports",{sync:true},function(a){set_vpn_ports(a,true)});daemon_cmd("connection_status",{sync:true},function(a){a=a.single;a!="down"&&(reconnect=true);set_connection_status(a)});setup_default_settings();if(!setting("user")||setting("first_run")){settings_window_show();setting("first_run",false)}setup_polling("connection_status",2E3,poll_connection_status);setup_polling("other_info",
5E3,function(){daemon_cmd("latency_status",{},function(a){set_latency_status(a)});daemon_cmd("regions",{},function(a){set_regions(a)});daemon_cmd("vpn_ports",{},function(a){set_vpn_ports(a)});daemon_cmd("need_upgrade",{},function(b){a(b.single)});daemon_cmd("forwarded_port",{},function(a){set_forwarded_port(a.single)});daemon_cmd("keepalive")});main_window().set_daemon_user=function(){daemon_cmd("set_user",{user:setting("user"),pass:setting("pass")})};main_window().set_daemon_user();daemon_cmd("portforward",
{value:setting("portforward")});daemon_cmd("killswitch",{value:setting("killswitch")});daemon_cmd("dnsleak",{value:setting("dnsleak")});daemon_cmd("ipv6leak",{value:setting("ipv6leak")});if(setting("connect_on_startup")&&TI.App.getArguments()[0]!="restart"&&connection_status=="down"){log("connect at startup");connect()}var f,l=function(){var a=(new Date).getTime();if(f&&a-f>3E4){log("sleep/resume detected, reconnecting");connection_status!="down"&&disconnect(true)}f=a;setTimeout(l,1E3)};l()};
