var TI;"undefined"!=typeof Titanium?TI=Titanium:"undefined"!=typeof Ti&&(TI=Ti);settings_window().settingsq=function(b){return $(b)};
$(document).ready(function(){var b=TI.API.getEnvironment().HOMEPATH;b&&b.match(/Documents and Settings/)&&$(".advancedWindow_ipv6leak").hide();("osx"==os()||"linux"==os())&&$(".advancedWindow_dnsleak").hide();$("#button_advanced").click(function(){300==TI.UI.currentWindow.width?("linux"==os()?TI.UI.currentWindow.setWidth(620):TI.UI.currentWindow.setWidth(600),$("#button_advanced").html("Simple"),$("#settingsWindow_right_container").show(),$("#app_version").show(),$("#button_enc").show()):($("#button_enc").hide(),
$("#settingsWindow_right_container").hide(),$("#app_version").hide(),TI.UI.currentWindow.setWidth(300),$("#button_advanced").html("Advanced"))});$("#button_enc").click(function(){"Encryption"==$("#button_enc").html()?($("#settingsWindow_right").hide(),$("#settingsWindow_right_enc").show(),$("#button_enc").html("Connection")):($("#button_enc").html("Encryption"),$("#settingsWindow_right_enc").hide(),$("#settingsWindow_right").show())});settings_window().check_enc=function(){"none"==$("#symmetric_cipher").val()||
"none"==$("#symmetric_auth").val()||$("#handshake_enc").val().match(/^ecdsa/)?$("#encryption_disclaimer").show():$("#encryption_disclaimer").hide()};$("#symmetric_cipher, #symmetric_auth, #handshake_enc").change(function(){settings_window().check_enc()});$("#run_on_startup").change(function(){daemon_cmd("run_on_startup",{value:$("#run_on_startup").prop("checked")})});$("#proto").change(function(){settings_window_update()});$("#button_save").click(function(){settings_window_save();settings_window().hide()});
$("#killswitch").click(function(){if(!$(this).attr("checked"))return!0;settings_window().setTopMost(!1);var a=confirm("Please only enable VPN Kill Switch if you really need it.  The Kill Switch requires modifying the Operating System's network settings and can in rare cases cause connectivity issues.  This feature WILL NOT work if you use MORE THAN ONE network interface on your computer simultaneously.\n\nAre you sure you wish to enable VPN Kill Switch?");settings_window().setTopMost(!0);return a});
$("#dnsleak").click(function(){if(!$(this).attr("checked"))return!0;settings_window().setTopMost(!1);var a=confirm("Please only enable DNS Leak Protection if you really need it.  DNS Leak Protection requires modifying the Operating System's network settings and can in rare cases cause connectivity issues.\n\nAre you sure you wish to enable DNS Leak Protection?");settings_window().setTopMost(!0);return a});document.oncontextmenu=function(){return!1};$("#username, #password").mousedown(function(a){if(2==
a.button){var b=$(this),c=a.pageX-this.offsetLeft,d=a.pageY;c<$(this).width()/2?($("#pastePopup").css("right",""),$("#pastePopup").css("left",c)):($("#pastePopup").css("left",""),$("#pastePopup").css("right",300-a.pageX));$("#pastePopup").css("top",d);$("#pastePopup").show();$("#paste_action").unbind("click");$(document).unbind("mouseleave");$(document).unbind("click");$("#paste_action").click(function(a){try{b.val(TI.UI.Clipboard.getText())}catch(c){}$("#pastePopup").hide();a.preventDefault()});
$(document).mouseleave(function(){$("#pastePopup").hide()});$(document).click(function(){$("#pastePopup").hide()});return!1}return!0});"osx"==os()&&$("#username, #password").keydown(function(a){a.metaKey&&86==a.keyCode&&($(this).val(TI.UI.Clipboard.getText()),a.preventDefault());a.metaKey&&65==a.keyCode&&($(this).select(),a.preventDefault())});$(document).keydown(function(a){a.ctrlKey&&76==a.keyCode&&(settings_window().hide(),confirm("Are you sure you want to send debugging log to Private Internet Access?")&&
daemon_cmd("mail_debug_log"))});main_window().setup()});
